### ISSUE TITLE
Fix StackBlitz config by renaming `.stackblitz` to `.stackblitzrc`

### ISSUE THREAD

**Issue by EricSimons** [edmundhung/remix-sandbox#24]
Hey Edmund- just ran across this and noticed your stackblitz branch is using the [incorrect file name](https://github.com/edmundhung/remix-sandbox/blob/stackblitz/.stackblitz) for config (`.stackblitz` instead of `.stackblitzrc`). With that change the dev command should automatically run on boot.

Let me know if there's anything else I (or our team) can do to help as y'all prepare for launch! 🚀

**Comment by edmundhung** [comment]
Hi Eric. Thanks for reaching out and offer helps on this! I fix the file name now but we are still blocked at the moment because most of the remix packages are hosted on a private registry. But this should be resolved once it is published to NPM next week. 🔥  I will let you know if I find other issues at that time :)

**Comment by edmundhung** [comment]
I got the packages installed on stackblitz now but it is stuck on building the files. Do you have any suggestions on how to debug this?
https://stackblitz.com/github/edmundhung/remix-sandbox/tree/stackblitz
